bool HQt_CheckLetterFromWord(QString x)
{
    /*
    Является ли буква символом из слова. Считается, что это или латинские буквы, или русские,
    или цифры или нижнее подчеркивание. Плюc некоторые знаки препинания, так как их нельзя переносить.
    Входные параметры:
     x - некая буква.
    Возвращаемое значение:
     true - буква из слова;
     false - не из слова.
    */
    bool VMHL_Result=false;

    if (x=="А") VMHL_Result=true;
    if (x=="а") VMHL_Result=true;
    if (x=="Б") VMHL_Result=true;
    if (x=="б") VMHL_Result=true;
    if (x=="В") VMHL_Result=true;
    if (x=="в") VMHL_Result=true;
    if (x=="Г") VMHL_Result=true;
    if (x=="г") VMHL_Result=true;
    if (x=="Д") VMHL_Result=true;
    if (x=="д") VMHL_Result=true;
    if (x=="Е") VMHL_Result=true;
    if (x=="е") VMHL_Result=true;
    if (x=="Ё") VMHL_Result=true;
    if (x=="ё") VMHL_Result=true;
    if (x=="Ж") VMHL_Result=true;
    if (x=="ж") VMHL_Result=true;
    if (x=="З") VMHL_Result=true;
    if (x=="з") VMHL_Result=true;
    if (x=="И") VMHL_Result=true;
    if (x=="и") VMHL_Result=true;
    if (x=="Й") VMHL_Result=true;
    if (x=="й") VMHL_Result=true;
    if (x=="К") VMHL_Result=true;
    if (x=="к") VMHL_Result=true;
    if (x=="Л") VMHL_Result=true;
    if (x=="л") VMHL_Result=true;
    if (x=="М") VMHL_Result=true;
    if (x=="м") VMHL_Result=true;
    if (x=="Н") VMHL_Result=true;
    if (x=="н") VMHL_Result=true;
    if (x=="О") VMHL_Result=true;
    if (x=="о") VMHL_Result=true;
    if (x=="П") VMHL_Result=true;
    if (x=="п") VMHL_Result=true;
    if (x=="Р") VMHL_Result=true;
    if (x=="р") VMHL_Result=true;
    if (x=="С") VMHL_Result=true;
    if (x=="с") VMHL_Result=true;
    if (x=="Т") VMHL_Result=true;
    if (x=="т") VMHL_Result=true;
    if (x=="У") VMHL_Result=true;
    if (x=="у") VMHL_Result=true;
    if (x=="Ф") VMHL_Result=true;
    if (x=="ф") VMHL_Result=true;
    if (x=="Х") VMHL_Result=true;
    if (x=="х") VMHL_Result=true;
    if (x=="Ц") VMHL_Result=true;
    if (x=="ц") VMHL_Result=true;
    if (x=="Ч") VMHL_Result=true;
    if (x=="ч") VMHL_Result=true;
    if (x=="Ш") VMHL_Result=true;
    if (x=="ш") VMHL_Result=true;
    if (x=="Щ") VMHL_Result=true;
    if (x=="щ") VMHL_Result=true;
    if (x=="Ъ") VMHL_Result=true;
    if (x=="ъ") VMHL_Result=true;
    if (x=="Ы") VMHL_Result=true;
    if (x=="ы") VMHL_Result=true;
    if (x=="Ь") VMHL_Result=true;
    if (x=="ь") VMHL_Result=true;
    if (x=="Э") VMHL_Result=true;
    if (x=="э") VMHL_Result=true;
    if (x=="Ю") VMHL_Result=true;
    if (x=="ю") VMHL_Result=true;
    if (x=="Я") VMHL_Result=true;
    if (x=="я") VMHL_Result=true;
    if (x=="A") VMHL_Result=true;
    if (x=="a") VMHL_Result=true;
    if (x=="B") VMHL_Result=true;
    if (x=="b") VMHL_Result=true;
    if (x=="C") VMHL_Result=true;
    if (x=="c") VMHL_Result=true;
    if (x=="D") VMHL_Result=true;
    if (x=="d") VMHL_Result=true;
    if (x=="E") VMHL_Result=true;
    if (x=="e") VMHL_Result=true;
    if (x=="F") VMHL_Result=true;
    if (x=="f") VMHL_Result=true;
    if (x=="G") VMHL_Result=true;
    if (x=="g") VMHL_Result=true;
    if (x=="H") VMHL_Result=true;
    if (x=="h") VMHL_Result=true;
    if (x=="I") VMHL_Result=true;
    if (x=="i") VMHL_Result=true;
    if (x=="J") VMHL_Result=true;
    if (x=="j") VMHL_Result=true;
    if (x=="K") VMHL_Result=true;
    if (x=="k") VMHL_Result=true;
    if (x=="L") VMHL_Result=true;
    if (x=="l") VMHL_Result=true;
    if (x=="M") VMHL_Result=true;
    if (x=="m") VMHL_Result=true;
    if (x=="N") VMHL_Result=true;
    if (x=="n") VMHL_Result=true;
    if (x=="O") VMHL_Result=true;
    if (x=="o") VMHL_Result=true;
    if (x=="P") VMHL_Result=true;
    if (x=="p") VMHL_Result=true;
    if (x=="Q") VMHL_Result=true;
    if (x=="q") VMHL_Result=true;
    if (x=="R") VMHL_Result=true;
    if (x=="r") VMHL_Result=true;
    if (x=="S") VMHL_Result=true;
    if (x=="s") VMHL_Result=true;
    if (x=="T") VMHL_Result=true;
    if (x=="t") VMHL_Result=true;
    if (x=="U") VMHL_Result=true;
    if (x=="u") VMHL_Result=true;
    if (x=="V") VMHL_Result=true;
    if (x=="v") VMHL_Result=true;
    if (x=="W") VMHL_Result=true;
    if (x=="w") VMHL_Result=true;
    if (x=="X") VMHL_Result=true;
    if (x=="x") VMHL_Result=true;
    if (x=="Y") VMHL_Result=true;
    if (x=="y") VMHL_Result=true;
    if (x=="Z") VMHL_Result=true;
    if (x=="z") VMHL_Result=true;
    if (x=="0") VMHL_Result=true;
    if (x=="1") VMHL_Result=true;
    if (x=="2") VMHL_Result=true;
    if (x=="3") VMHL_Result=true;
    if (x=="4") VMHL_Result=true;
    if (x=="5") VMHL_Result=true;
    if (x=="6") VMHL_Result=true;
    if (x=="7") VMHL_Result=true;
    if (x=="8") VMHL_Result=true;
    if (x=="9") VMHL_Result=true;
    if (x=="_") VMHL_Result=true;
    if (x==".") VMHL_Result=true;
    if (x==",") VMHL_Result=true;
    if (x==":") VMHL_Result=true;
    if (x=="!") VMHL_Result=true;
    if (x=="?") VMHL_Result=true;

    return VMHL_Result;
}