bool HQt_CheckLetterFromWord(QString x)
{
    /*
    Является ли буква символом из слова. Считается, что это или латинские буквы, или русские,
    или цифры или нижнее подчеркивание. Плюc некоторые знаки препинания, так как их нельзя переносить.
    Входные параметры:
     x - некая буква.
    Возвращаемое значение:
     true - буква из слова;
     false - не из слова.
    */
    bool VHQt_Result=false;

    if (x=="А") VHQt_Result=true;
    if (x=="а") VHQt_Result=true;
    if (x=="Б") VHQt_Result=true;
    if (x=="б") VHQt_Result=true;
    if (x=="В") VHQt_Result=true;
    if (x=="в") VHQt_Result=true;
    if (x=="Г") VHQt_Result=true;
    if (x=="г") VHQt_Result=true;
    if (x=="Д") VHQt_Result=true;
    if (x=="д") VHQt_Result=true;
    if (x=="Е") VHQt_Result=true;
    if (x=="е") VHQt_Result=true;
    if (x=="Ё") VHQt_Result=true;
    if (x=="ё") VHQt_Result=true;
    if (x=="Ж") VHQt_Result=true;
    if (x=="ж") VHQt_Result=true;
    if (x=="З") VHQt_Result=true;
    if (x=="з") VHQt_Result=true;
    if (x=="И") VHQt_Result=true;
    if (x=="и") VHQt_Result=true;
    if (x=="Й") VHQt_Result=true;
    if (x=="й") VHQt_Result=true;
    if (x=="К") VHQt_Result=true;
    if (x=="к") VHQt_Result=true;
    if (x=="Л") VHQt_Result=true;
    if (x=="л") VHQt_Result=true;
    if (x=="М") VHQt_Result=true;
    if (x=="м") VHQt_Result=true;
    if (x=="Н") VHQt_Result=true;
    if (x=="н") VHQt_Result=true;
    if (x=="О") VHQt_Result=true;
    if (x=="о") VHQt_Result=true;
    if (x=="П") VHQt_Result=true;
    if (x=="п") VHQt_Result=true;
    if (x=="Р") VHQt_Result=true;
    if (x=="р") VHQt_Result=true;
    if (x=="С") VHQt_Result=true;
    if (x=="с") VHQt_Result=true;
    if (x=="Т") VHQt_Result=true;
    if (x=="т") VHQt_Result=true;
    if (x=="У") VHQt_Result=true;
    if (x=="у") VHQt_Result=true;
    if (x=="Ф") VHQt_Result=true;
    if (x=="ф") VHQt_Result=true;
    if (x=="Х") VHQt_Result=true;
    if (x=="х") VHQt_Result=true;
    if (x=="Ц") VHQt_Result=true;
    if (x=="ц") VHQt_Result=true;
    if (x=="Ч") VHQt_Result=true;
    if (x=="ч") VHQt_Result=true;
    if (x=="Ш") VHQt_Result=true;
    if (x=="ш") VHQt_Result=true;
    if (x=="Щ") VHQt_Result=true;
    if (x=="щ") VHQt_Result=true;
    if (x=="Ъ") VHQt_Result=true;
    if (x=="ъ") VHQt_Result=true;
    if (x=="Ы") VHQt_Result=true;
    if (x=="ы") VHQt_Result=true;
    if (x=="Ь") VHQt_Result=true;
    if (x=="ь") VHQt_Result=true;
    if (x=="Э") VHQt_Result=true;
    if (x=="э") VHQt_Result=true;
    if (x=="Ю") VHQt_Result=true;
    if (x=="ю") VHQt_Result=true;
    if (x=="Я") VHQt_Result=true;
    if (x=="я") VHQt_Result=true;
    if (x=="A") VHQt_Result=true;
    if (x=="a") VHQt_Result=true;
    if (x=="B") VHQt_Result=true;
    if (x=="b") VHQt_Result=true;
    if (x=="C") VHQt_Result=true;
    if (x=="c") VHQt_Result=true;
    if (x=="D") VHQt_Result=true;
    if (x=="d") VHQt_Result=true;
    if (x=="E") VHQt_Result=true;
    if (x=="e") VHQt_Result=true;
    if (x=="F") VHQt_Result=true;
    if (x=="f") VHQt_Result=true;
    if (x=="G") VHQt_Result=true;
    if (x=="g") VHQt_Result=true;
    if (x=="H") VHQt_Result=true;
    if (x=="h") VHQt_Result=true;
    if (x=="I") VHQt_Result=true;
    if (x=="i") VHQt_Result=true;
    if (x=="J") VHQt_Result=true;
    if (x=="j") VHQt_Result=true;
    if (x=="K") VHQt_Result=true;
    if (x=="k") VHQt_Result=true;
    if (x=="L") VHQt_Result=true;
    if (x=="l") VHQt_Result=true;
    if (x=="M") VHQt_Result=true;
    if (x=="m") VHQt_Result=true;
    if (x=="N") VHQt_Result=true;
    if (x=="n") VHQt_Result=true;
    if (x=="O") VHQt_Result=true;
    if (x=="o") VHQt_Result=true;
    if (x=="P") VHQt_Result=true;
    if (x=="p") VHQt_Result=true;
    if (x=="Q") VHQt_Result=true;
    if (x=="q") VHQt_Result=true;
    if (x=="R") VHQt_Result=true;
    if (x=="r") VHQt_Result=true;
    if (x=="S") VHQt_Result=true;
    if (x=="s") VHQt_Result=true;
    if (x=="T") VHQt_Result=true;
    if (x=="t") VHQt_Result=true;
    if (x=="U") VHQt_Result=true;
    if (x=="u") VHQt_Result=true;
    if (x=="V") VHQt_Result=true;
    if (x=="v") VHQt_Result=true;
    if (x=="W") VHQt_Result=true;
    if (x=="w") VHQt_Result=true;
    if (x=="X") VHQt_Result=true;
    if (x=="x") VHQt_Result=true;
    if (x=="Y") VHQt_Result=true;
    if (x=="y") VHQt_Result=true;
    if (x=="Z") VHQt_Result=true;
    if (x=="z") VHQt_Result=true;
    if (x=="0") VHQt_Result=true;
    if (x=="1") VHQt_Result=true;
    if (x=="2") VHQt_Result=true;
    if (x=="3") VHQt_Result=true;
    if (x=="4") VHQt_Result=true;
    if (x=="5") VHQt_Result=true;
    if (x=="6") VHQt_Result=true;
    if (x=="7") VHQt_Result=true;
    if (x=="8") VHQt_Result=true;
    if (x=="9") VHQt_Result=true;
    if (x=="_") VHQt_Result=true;
    if (x==".") VHQt_Result=true;
    if (x==",") VHQt_Result=true;
    if (x==":") VHQt_Result=true;
    if (x=="!") VHQt_Result=true;
    if (x=="?") VHQt_Result=true;

    return VHQt_Result;
}